# US Tickers Retrieval

## Introduction

This script provides a powerful tool to access and manipulate stock ticker data from the Nasdaq website via API. It allows users to download, filter, and analyze ticker information efficiently. The primary data source is: https://www.nasdaq.com/market-activity/stocks/screener

## Setup and Initial Data Retrieval

First, we import the necessary modules and initialize our `Tickers` class:

In [1]:
import tickers as tk
import pandas as pd
import numpy as np

To download the data, we simply instantiate the `Tickers()` class. The retrieved dataset is stored in the `.data` attribute:

In [2]:
tickers = tk.Tickers()
print(len(tickers.data))

5514

In [3]:
tickers.data.head(10)

,symbol,name,exchange,marketCap,sector,industry,lastsale,volume,ipoyear,country,url
0,A,Agilent Technologies Inc. Common Stock,nyse,38367196759,Industrials,Biotechnology: Laboratory Analytical Instruments,$135.65,1551941,1999,United States,/market-activity/stocks/a
1,AA,Alcoa Corporation Common Stock,nyse,15162344074,Industrials,Aluminum,$58.55,10146105,2016,United States,/market-activity/stocks/aa
2,AACB,Artius II Acquisition Inc. Class A Ordinary Sh...,nasdaq,0,,,$10.38,66521,2025,United States,/market-activity/stocks/aacb
5,AACG,ATA Creativity Global American Depositary Shares,nasdaq,35102526,Real Estate,Other Consumer Services,$1.10,15771,2008,China,/market-activity/stocks/aacg
6,AAL,American Airlines Group Inc. Common Stock,nasdaq,9617460232,Consumer Discretionary,Air Freight/Delivery Services,$14.57,42011818,,United States,/market-activity/stocks/aal
7,AAM,AA Mission Acquisition Corp. Class A Ordinary ...,nyse,0,,,$10.675,16203,2024,,/market-activity/stocks/aam
8,AAME,Atlantic American Corporation Common Stock,nasdaq,56500322,Finance,Life Insurance,$2.77,32175,,United States,/market-activity/stocks/aame
9,AAMI,Acadian Asset Management Inc. Common Stock,nyse,1978285248,Finance,Investment Managers,$55.40,191488,2014,United Kingdom,/market-activity/stocks/aami
10,AAOI,Applied Optoelectronics Inc. Common Stock,nasdaq,2382233969,Technology,Semiconductors,$34.89,3240497,2013,United States,/market-activity/stocks/aaoi
11,AAON,AAON Inc. Common Stock,nasdaq,7630335401,Industrials,Industrial Machinery/Components,$93.47,483427,,United States,/market-activity/stocks/aaon

In [4]:
tickers.data.describe()

,symbol,name,exchange,marketCap,sector,industry,lastsale,volume,ipoyear,country,url
count,5514,5514,5514,5514,5514,5514,5514,5514,5514,5514,5514
unique,5514,5511,3,5360,13,153,3847,5500,63,61,5514
top,A,Berkshire Hathaway Inc.,nasdaq,0,Health Care,Biotechnology: Pharmaceutical Preparations,$1.53,29963,,United States,/market-activity/stocks/a
freq,1,2,3315,155,1039,513,13,2,2281,4045,1

## Core Functionalities: Ticker List

The primary goal of this script is to generate a curated list of stock tickers for further analysis or downloading. This list is dynamically stored in the `.ticker_list` attribute, which updates as we apply filters to the dataset. Initially, it contains all tickers from the dataset:

In [5]:
print(len(tickers.tickers_list))
tickers.tickers_list[:30]

5514

['A',
 'AA',
 'AACB',
 'AACG',
 'AAL',
 'AAM',
 'AAME',
 'AAMI',
 'AAOI',
 'AAON',
 'AAP',
 'AAPG',
 'AAPL',
 'AARD',
 'AAT',
 'AAUC',
 'AB',
 'ABAT',
 'ABBV',
 'ABCB',
 'ABCL',
 'ABEO',
 'ABEV',
 'ABG',
 'ABLV',
 'ABM',
 'ABNB',
 'ABOS',
 'ABP',
 'ABR']

## Data Analysis and Filtering

The `Tickers` class provides several methods to analyze and filter the data. These methods are also implemented in the Streamlit app for user-friendly interaction.

### Top Stocks by Market Capitalization

To retrieve the top 30 stocks by market capitalization:

In [6]:
tickers.get_biggest_n_tickers(top_n=30)
tickers.data

,symbol,name,exchange,marketCap,sector,industry,lastsale,volume,ipoyear,country,url
4313,NVDA,NVIDIA Corporation Common Stock,nasdaq,4531221000000,Technology,Semiconductors,$186.47,124415866,1999,United States,/market-activity/stocks/nvda
2632,GOOG,Alphabet Inc. Class C Capital Stock,nasdaq,4025430530000,Technology,Computer Software: Programming Data Processing,$333.59,18460391,2004,United States,/market-activity/stocks/goog
2633,GOOGL,Alphabet Inc. Class A Common Stock,nasdaq,4021448420000,Technology,Computer Software: Programming Data Processing,$333.26,26010027,2004,United States,/market-activity/stocks/googl
14,AAPL,Apple Inc. Common Stock,nasdaq,3753997279660,Technology,Computer Manufacturing,$255.41,55822417,1980,United States,/market-activity/stocks/aapl
3966,MSFT,Microsoft Corporation Common Stock,nasdaq,3495298563593,Technology,Computer Software: Prepackaged Software,$470.28,29246908,1986,United States,/market-activity/stocks/msft
356,AMZN,Amazon.com Inc. Common Stock,nasdaq,2548761301343,Consumer Discretionary,Catalog/Specialty Distribution,$238.42,32734075,1997,United States,/market-activity/stocks/amzn
6019,TSM,Taiwan Semiconductor Manufacturing Company Ltd.,nyse,1725615935256,Technology,Semiconductors,$332.71,8629064,1997,Taiwan,/market-activity/stocks/tsm
3783,META,Meta Platforms Inc. Class A Common Stock,nasdaq,1694701935119,Technology,Computer Software: Programming Data Processing,$672.36,16259384,2012,United States,/market-activity/stocks/meta
596,AVGO,Broadcom Inc. Common Stock,nasdaq,1540202793605,Technology,Semiconductors,$324.85,24950008,2009,United States,/market-activity/stocks/avgo
6017,TSLA,Tesla Inc. Common Stock,nasdaq,1447396501478,Industrials,Auto Manufacturing,$435.20,49199410,2010,United States,/market-activity/stocks/tsla
971,BRK/A,Berkshire Hathaway Inc.,nyse,1068472291080,,,$726420.00,463,,United States,/market-activity/stocks/brk/a
972,BRK/B,Berkshire Hathaway Inc.,nyse,1066685358537,,,$483.47,5074295,,United States,/market-activity/stocks/brk/b
3549,LLY,Eli Lilly and Company Common Stock,nyse,1004706587752,Health Care,Biotechnology: Pharmaceutical Preparations,$1062.75,2243836,,United States,/market-activity/stocks/lly
6456,WMT,Walmart Inc. Common Stock,nasdaq,937610441645,Consumer Discretionary,Department/Specialty Retail Stores,$117.64,19543083,,United States,/market-activity/stocks/wmt
3263,JPM,JP Morgan Chase & Co. Common Stock,nyse,819509841287,Finance,Major Banks,$301.04,11736964,,United States,/market-activity/stocks/jpm
6196,V,Visa Inc.,nyse,632581443683,Real Estate,Real Estate,$328.49,7525247,,United States,/market-activity/stocks/v
6544,XOM,Exxon Mobil Corporation Common Stock,nyse,568642611392,Energy,Integrated oil Companies,$134.84,16051501,,United States,/market-activity/stocks/xom
503,ASML,ASML Holding N.V. New York Registry Shares,nasdaq,555847545662,Technology,Industrial Machinery/Components,$1413.35,2000475,1995,Netherlands,/market-activity/stocks/asml
3255,JNJ,Johnson & Johnson Common Stock,nyse,533634772142,Health Care,Biotechnology: Pharmaceutical Preparations,$221.49,6856732,,United States,/market-activity/stocks/jnj
4492,ORCL,Oracle Corporation Common Stock,nyse,524173837200,Technology,Computer Software: Prepackaged Software,$182.44,21060657,1986,United States,/market-activity/stocks/orcl
3670,MA,Mastercard Incorporated Common Stock,nyse,473567090401,Real Estate,Real Estate,$527.36,4838782,2006,United States,/market-activity/stocks/ma
4003,MU,Micron Technology Inc. Common Stock,nasdaq,437924398362,Technology,Semiconductors,$389.09,29089033,,United States,/market-activity/stocks/mu
1470,COST,Costco Wholesale Corporation Common Stock,nasdaq,433957807052,Consumer Discretionary,Department/Specialty Retail Stores,$977.67,2456160,,United States,/market-activity/stocks/cost
320,AMD,Advanced Micro Devices Inc. Common Stock,nasdaq,409143119417,Technology,Semiconductors,$251.31,30590308,,United States,/market-activity/stocks/amd
4750,PLTR,Palantir Technologies Inc. Class A Common Stock,nasdaq,399154083525,Technology,Computer Software: Prepackaged Software,$167.47,22698349,,United States,/market-activity/stocks/pltr
645,BABA,Alibaba Group Holding Limited American Deposit...,nyse,395741221746,Real Estate,Real Estate,$171.37,10133309,2014,China,/market-activity/stocks/baba
20,ABBV,AbbVie Inc. Common Stock,nyse,390185505207,Health Care,Biotechnology: Pharmaceutical Preparations,$220.77,6549696,2012,United States,/market-activity/stocks/abbv
2778,HD,Home Depot Inc. (The) Common Stock,nyse,384795054297,Consumer Discretionary,RETAIL: Building Materials,$386.53,3984724,,United States,/market-activity/stocks/hd
646,BAC,Bank of America Corporation Common Stock,nyse,379875818511,Finance,Major Banks,$52.02,27707380,,United States,/market-activity/stocks/bac
4139,NFLX,Netflix Inc. Common Stock,nasdaq,361839296255,Consumer Discretionary,Consumer Electronics/Video Chains,$85.70,40828353,2002,United States,/market-activity/stocks/nflx

Important notes:
1. These methods modify the `.data` attribute in-place.
2. The `.original_dataset` attribute remains unmodified, serving as a backup of the clean original dataset.

In [7]:
print(len(tickers.data))
print(len(tickers.original_dataset))

30
5514

If needed, you can reset the `.data` attribute to its original state using the `.reset_data()` method:

In [8]:
tickers.reset_data()
print(len(tickers.data))
print(len(tickers.original_dataset))

5514
5514

### Applying Filters

Let's explore various filtering options:

In [9]:
# List of unique exchanges
print(tickers.original_dataset.exchange.unique())
# List of unique sectors
print(tickers.original_dataset.sector.unique())

['nyse' 'nasdaq' 'amex']
['Industrials' '' 'Real Estate' 'Consumer Discretionary' 'Finance'
 'Technology' 'Health Care' 'Basic Materials' 'Consumer Staples' 'Energy'
 'Miscellaneous' 'Telecommunications' 'Utilities']

In [10]:
tickers.apply_filters(exchange='nyse', sectors='Utilities')
print(len(tickers.data))
tickers.data

95

,symbol,name,exchange,marketCap,sector,industry,lastsale,volume,ipoyear,country,url
129,AEE,Ameren Corporation Common Stock,nyse,27928600077,Utilities,Power Generation,$103.25,1350051,,United States,/market-activity/stocks/aee
148,AES,The AES Corporation Common Stock,nyse,10411208201,Utilities,Electric Utilities: Central,$14.62,8523182,,United States,/market-activity/stocks/aes
308,AM,Antero Midstream Corporation Common Stock,nyse,8901579750,Utilities,Natural Gas Distribution,$18.69,1930485,2017,United States,/market-activity/stocks/am
433,AQN,Algonquin Power & Utilities Corp. Common Shares,nyse,4947504549,Utilities,Electric Utilities: Central,$6.44,4118101,2016,United States,/market-activity/stocks/aqn
469,AROC,Archrock Inc. Common Stock,nyse,4940162815,Utilities,Natural Gas Distribution,$28.17,1047566,,United States,/market-activity/stocks/aroc
...,...,...,...,...,...,...,...,...,...,...,...
6399,WES,Western Midstream Partners LP Common Units Rep...,nyse,16572786350,Utilities,Natural Gas Distribution,$40.62,1230520,2012,United States,/market-activity/stocks/wes
6451,WM,Waste Management Inc. Common Stock,nyse,92760138493,Utilities,Environmental Services,$230.25,2106038,,United States,/market-activity/stocks/wm
6452,WMB,Williams Companies Inc. (The) Common Stock,nyse,78512160959,Utilities,Natural Gas Distribution,$64.29,7559729,,United States,/market-activity/stocks/wmb
6501,WTRG,Essential Utilities Inc. Common Stock,nyse,11126597486,Utilities,Water Supply,$39.32,1786615,,United States,/market-activity/stocks/wtrg
6539,XIFR,XPLR Infrastructure LP Common Units representi...,nyse,911473556,Utilities,Electric Utilities: Central,$9.70,1055807,2014,United States,/market-activity/stocks/xifr

In [11]:
tickers.apply_filters(exchange=['nyse','amex'], sectors=['Finance', 'Consumer Staples'])
print(len(tickers.data))
tickers.data

472

,symbol,name,exchange,marketCap,sector,industry,lastsale,volume,ipoyear,country,url
9,AAMI,Acadian Asset Management Inc. Common Stock,nyse,1978285248,Finance,Investment Managers,$55.40,191488,2014,United Kingdom,/market-activity/stocks/aami
18,AB,AllianceBernstein Holding L.P. Units,nyse,3810797352,Finance,Investment Managers,$41.88,1624555,,United States,/market-activity/stocks/ab
21,ABCB,Ameris Bancorp Common Stock,nyse,5492537578,Finance,Major Banks,$80.40,352865,1994,United States,/market-activity/stocks/abcb
24,ABEV,Ambev S.A. American Depositary Shares (Each re...,nyse,43838365830,Consumer Staples,Beverages (Production/Distribution),$2.80,26485236,2013,Brazil,/market-activity/stocks/abev
43,ABX,Abacus Global Management Inc. Class A Common S...,nyse,811348697,Finance,Investment Managers,$8.30,283763,,United States,/market-activity/stocks/abx
...,...,...,...,...,...,...,...,...,...,...,...
6571,XXI,Twenty One Capital Inc. Class A Common Stock,nyse,5308835933,Finance,Finance: Consumer Services,$8.15,847731,2025,,/market-activity/stocks/xxi
6573,XYF,X Financial American Depositary Shares each re...,nyse,235950512,Finance,Finance: Consumer Services,$5.59,424475,2018,Cayman Islands,/market-activity/stocks/xyf
6576,XZO,Exzeo Group Inc. Common Stock,nyse,1935243881,Finance,Property-Casualty Insurers,$21.32,34818,2025,,/market-activity/stocks/xzo
6603,YRD,Yiren Digital Ltd. American Depositary Shares ...,nyse,342169677,Finance,Finance: Consumer Services,$3.96,38531,2015,China,/market-activity/stocks/yrd
6657,ZVIA,Zevia PBC Class A Common Stock,nyse,153758177,Consumer Staples,Beverages (Production/Distribution),$2.05,2424522,2021,United States,/market-activity/stocks/zvia

## Market Capitalization Filtering

The script provides functionality to filter stocks based on market capitalization:

In [15]:
# highest market capitalization of all the stocks in the dataset
print(f'The highest market capitalization in USD Millions is {tickers.max_cap / 1_000_000}')

The highest market capitalization in USD Millions is 4531221.0

To facilitate market cap filtering, we use a helper function that creates a logarithmic scale of 10 market cap values. This approach accounts for the skewed distribution of market caps in US stocks, where a few companies have enormous capitalizations while the majority have more moderate values.

In [16]:
log_ladder_cap = tk.generate_mktcap_values(tickers.max_cap)
print(log_ladder_cap)

[0, 5500000, 30200000, 166300000, 914600000, 5000000000, 27000000000, 150000000000, 830000000000, 4700000000000]

### Combining Filters

We can combine multiple filters for more precise selection:

In [18]:
tickers.apply_filters(sectors=['Finance', 'Consumer Staples', 'Industrials'], mktcap_min=log_ladder_cap[4], mktcap_max=log_ladder_cap[9])
print(len(tickers.data))
tickers.data.sort_values('marketCap',ascending=False)

846

,symbol,name,exchange,marketCap,sector,industry,lastsale,volume,ipoyear,country,url
6017,TSLA,Tesla Inc. Common Stock,nasdaq,1447396501478,Industrials,Auto Manufacturing,$435.20,49199410,2010,United States,/market-activity/stocks/tsla
3263,JPM,JP Morgan Chase & Co. Common Stock,nyse,819509841287,Finance,Major Banks,$301.04,11736964,,United States,/market-activity/stocks/jpm
646,BAC,Bank of America Corporation Common Stock,nyse,379875818511,Finance,Major Banks,$52.02,27707380,,United States,/market-activity/stocks/bac
3361,KO,Coca-Cola Company (The) Common Stock,nyse,312124737793,Consumer Staples,Beverages (Production/Distribution),$72.56,14006794,,United States,/market-activity/stocks/ko
1128,CAT,Caterpillar Inc. Common Stock,nyse,297597584688,Industrials,Construction/Ag Equipment/Trucks,$635.92,2532220,,United States,/market-activity/stocks/cat
...,...,...,...,...,...,...,...,...,...,...,...
3911,MOFG,MidWestOne Financial Gp Common Stock,nasdaq,938790580,Finance,Major Banks,$45.50,154114,,United States,/market-activity/stocks/mofg
1476,CPAC,Cementos Pacasmayo S.A.A. American Depositary ...,nyse,935053801,Industrials,Building Materials,$11.03,64663,,Peru,/market-activity/stocks/cpac
2092,ESQ,Esquire Financial Holdings Inc. Common Stock,nasdaq,933638519,Finance,Commercial Banks,$109.00,84667,2017,United States,/market-activity/stocks/esq
4074,NBN,Northeast Bank Common Stock,nasdaq,928852500,Finance,Major Banks,$114.25,86752,,United States,/market-activity/stocks/nbn
2871,HQH,abrdn Healthcare Investors Shares of Beneficia...,nyse,925096406,Finance,Finance Companies,$19.54,115227,1987,United States,/market-activity/stocks/hqh

Let's grab only the top 25 of the selected stocks.

In [19]:
tickers.get_biggest_n_tickers(top_n=25)
tickers.data

,symbol,name,exchange,marketCap,sector,industry,lastsale,volume,ipoyear,country,url
6017,TSLA,Tesla Inc. Common Stock,nasdaq,1447396501478,Industrials,Auto Manufacturing,$435.20,49199410,2010,United States,/market-activity/stocks/tsla
3263,JPM,JP Morgan Chase & Co. Common Stock,nyse,819509841287,Finance,Major Banks,$301.04,11736964,,United States,/market-activity/stocks/jpm
646,BAC,Bank of America Corporation Common Stock,nyse,379875818511,Finance,Major Banks,$52.02,27707380,,United States,/market-activity/stocks/bac
3361,KO,Coca-Cola Company (The) Common Stock,nyse,312124737793,Consumer Staples,Beverages (Production/Distribution),$72.56,14006794,,United States,/market-activity/stocks/ko
1128,CAT,Caterpillar Inc. Common Stock,nyse,297597584688,Industrials,Construction/Ag Equipment/Trucks,$635.92,2532220,,United States,/market-activity/stocks/cat
5918,TM,Toyota Motor Corporation Common Stock,nyse,294409953471,Industrials,Auto Manufacturing,$225.62,277467,,Japan,/market-activity/stocks/tm
2885,HSBC,HSBC Holdings plc. Common Stock,nyse,292288231937,Finance,Savings Institutions,$85.09,1268021,,United Kingdom,/market-activity/stocks/hsbc
3954,MS,Morgan Stanley Common Stock,nyse,289063577485,Finance,Investment Bankers/Brokers/Service,$181.88,6388763,,United States,/market-activity/stocks/ms
2687,GS,Goldman Sachs Group Inc. (The) Common Stock,nyse,279491382260,Finance,Investment Bankers/Brokers/Service,$931.86,2653182,1999,United States,/market-activity/stocks/gs
6406,WFC,Wells Fargo & Company Common Stock,nyse,276396393923,Finance,Major Banks,$88.05,13046622,,United States,/market-activity/stocks/wfc
5183,RTX,RTX Corporation Common Stock,nyse,260284057100,Industrials,Aerospace,$194.13,6658077,,United States,/market-activity/stocks/rtx
628,AXP,American Express Company Common Stock,nyse,250225362952,Finance,Finance: Consumer Services,$363.25,2131144,,United States,/market-activity/stocks/axp
5926,TMO,Thermo Fisher Scientific Inc Common Stock,nyse,235426183931,Industrials,Industrial Machinery/Components,$626.62,1758275,,United States,/market-activity/stocks/tmo
5213,RY,Royal Bank Of Canada Common Stock,nyse,234283469665,Finance,Commercial Banks,$167.32,2382022,,Canada,/market-activity/stocks/ry
4007,MUFG,Mitsubishi UFJ Financial Group Inc. Common Stock,nyse,211838639922,Finance,Commercial Banks,$17.85,4181100,,Japan,/market-activity/stocks/mufg
1082,C,Citigroup Inc. Common Stock,nyse,205443540376,Finance,Major Banks,$114.82,11725773,,United States,/market-activity/stocks/c
4663,PEP,PepsiCo Inc. Common Stock,nasdaq,199453903596,Consumer Staples,Beverages (Production/Distribution),$145.87,6587176,,United States,/market-activity/stocks/pep
644,BA,Boeing Company (The) Common Stock,nyse,188830517115,Industrials,Aerospace,$248.43,8444983,,United States,/market-activity/stocks/ba
5250,SAN,Banco Santander S.A. Sponsored ADR (Spain),nyse,186492560934,Finance,Commercial Banks,$12.67,2434905,,Spain,/market-activity/stocks/san
5297,SCHW,Charles Schwab Corporation (The) Common Stock,nyse,182917871104,Finance,Investment Bankers/Brokers/Service,$102.94,7357351,,United States,/market-activity/stocks/schw
873,BLK,BlackRock Inc. Common Stock,nyse,174007950480,Finance,Investment Bankers/Brokers/Service,$1121.54,739322,1999,United States,/market-activity/stocks/blk
1750,DHR,Danaher Corporation Common Stock,nyse,167200005058,Industrials,Industrial Machinery/Components,$236.71,4470989,,United States,/market-activity/stocks/dhr
2779,HDB,HDFC Bank Limited Common Stock,nyse,164544552200,Finance,Commercial Banks,$32.15,5042185,2001,India,/market-activity/stocks/hdb
5575,SPGI,S&P Global Inc. Common Stock,nyse,162067644000,Finance,Finance: Consumer Services,$535.23,1022068,,United States,/market-activity/stocks/spgi
5812,TD,Toronto Dominion Bank (The) Common Stock,nyse,161996587560,Finance,Commercial Banks,$94.89,1687986,,Canada,/market-activity/stocks/td

## Finalizing and Exporting Results

Finally, we can view the resulting ticker list and export it to a .csv file. By default, the file is saved in the local Downloads folder:

In [20]:
tickers.tickers_list

['TSLA',
 'JPM',
 'BAC',
 'KO',
 'CAT',
 'TM',
 'HSBC',
 'MS',
 'GS',
 'WFC',
 'RTX',
 'AXP',
 'TMO',
 'RY',
 'MUFG',
 'C',
 'PEP',
 'BA',
 'SAN',
 'SCHW',
 'BLK',
 'DHR',
 'HDB',
 'SPGI',
 'TD']

In [21]:
tickers.save_tickers()